### ISSUE TITLE
How to generate

### ISSUE THREAD

**Issue by Xeroner** [dragonbanshee/node-steam-parentbot#12]
How to generate Mobile Auth Code when bot is running ?

**Comment by mert574** [comment]
use **steam-totp** for that.

```
var ParentBot = require('steam-parentbot');
var SteamTotp = require('steam-totp');
var util = require('util');
var botMain = function () { botMain.super_.apply(this, arguments); }

util.inherits(botMain, ParentBot);

var ChildBot = new botMain('usern','passw',{
    sharedSecret:'sharedSecret',
});

var _2facode = SteamTotp.generateAuthCode(ChildBot.sharedSecret);
console.log(_2facode);
```

**Comment by kjsmita6** [comment]
Steam-totp is included in parentbot so there's no need to require it, just use ParentBot.SteamTotp. There also is no real point in generating the code since parentbot does it on login but you can do what you want. 

Edit: nvm totp can be done like that,  you need to require it separately until I fix that.

**Comment by Xeroner** [comment]
Thx :+1:

**Comment by CodeLuca** [comment]
Where do you get the shared secret?

**Comment by CodeLuca** [comment]
I really like the look of this module, im just confused as to where the shared secret comes from.

**Comment by kjsmita6** [comment]
@CodeLuca the shared_secret is generated from when 2FA is activated on the bot. If you do it using this module the shared_secret, among other things, is saved to a file called username.2fa_info.
