### ISSUE TITLE
Problem with hold duration!

### ISSUE THREAD

**Issue by Xeroner** [dragonbanshee/node-steam-parentbot#21]
Why my bot is accepting offers with holdl duration...
Help please.

> http://pastebin.com/DbvWp9eq

**Comment by mert574** [comment]
I didn't checked your code but node library "steam-tradeoffers" is broken. Edit your parentbot to make it use tradeoffers-manager

Also: Steam wasn't stable today.

**Comment by kjsmita6** [comment]
@infam0us I have no plans to remove steam-tradeoffers since it works fine for me. Please remember, quoting from the readme, `I made this (mainly for myself)`. Since I have no need to do anything with trade durations, I have no plans of changing it. Also I have no experience with trade-offers-manager, so if I add it it will most likely not work.

~~However I will take a look and see if it is worth it to change.~~
I have looked and decided that there is no need to add this as most of the functionality can be completed using steam-tradeoffers.

If there is a problem that you believe is a bug in steam-tradeoffers, you must open an issue [here](https://github.com/Alex7Kom/node-steam-tradeoffers/issues).

**Comment by andrewda** [comment]
It's not difficult to add the `node-steam-tradeoffers` to the parentbot yourself.
